services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      TZ: Asia/Bangkok
      LOTTO_DB_URL: ${LOTTO_DB_URL}
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy