"""
Square news poster for the hot-news photo post — poster.py

Two layouts, both 1080x1080 with three Thai headline lines and a photo credit:
  portrait — the person cut out of the source photo (rembg, face untouched) over an
             AI background (flux-2-klein-4b, generated by the caller)
  scene    — the source photo itself, colour-graded, over a blurred copy of itself

Thai text goes through Pillow's raqm layout (needs libfribidi/libharfbuzz at runtime):
ffmpeg drawtext drops stacked marks such as the ์ in ธิ์ or the ้ in ฮั้ว.
"""

from pathlib import Path

from PIL import Image, ImageDraw, ImageEnhance, ImageFilter, ImageFont, ImageOps

FONT = str(Path(__file__).parent / "assets" / "Kanit-Black.ttf")
S = 1080
TEXT_TOP = 700
MAX_TEXT_W = 1000
# (default size, fill, stroke, red band behind)
LINE_STYLE = [(88, "white", 5, True), (140, (255, 214, 31), 8, False), (72, "white", 5, False)]
LINE_Y = [TEXT_TOP, TEXT_TOP + 100, TEXT_TOP + 270]
MIN_PERSON, MAX_PERSON = 0.08, 0.85  # share of the photo the cutout mask must cover


def cutout(photo: Image.Image) -> Image.Image | None:
    """Person cutout (RGBA, cropped), or None when the mask is too small/large to be one clear person."""
    from rembg import new_session, remove  # heavy import: onnxruntime + model load

    out = remove(photo.convert("RGB"), session=new_session("u2net_human_seg"))
    alpha = out.getchannel("A")
    cover = sum(alpha.point(lambda v: 1 if v > 128 else 0).getdata()) / (alpha.width * alpha.height)
    print(f"[POSTER] cutout covers {cover:.0%}")
    if not MIN_PERSON <= cover <= MAX_PERSON:
        return None
    return out.crop(out.getbbox())


def _portrait(person: Image.Image, background: Image.Image) -> Image.Image:
    bg = ImageEnhance.Brightness(ImageOps.fit(background.convert("RGB"), (S, S))).enhance(0.8)
    ph = 760
    p = person.resize((round(person.width * ph / person.height), ph), Image.LANCZOS)
    if p.width > S:  # very wide cutouts (two people, arms out): fit width instead
        p = p.resize((S, round(p.height * S / p.width)), Image.LANCZOS)
    bg.paste(p, ((S - p.width) // 2, TEXT_TOP + 50 - p.height), p)
    return bg


def _scene(photo: Image.Image) -> Image.Image:
    photo = photo.convert("RGB")
    bg = ImageOps.fit(photo, (S, S)).filter(ImageFilter.GaussianBlur(40))
    bg = ImageEnhance.Brightness(bg).enhance(0.6)
    top = ImageOps.fit(photo, (S, 680))
    top = ImageEnhance.Color(ImageEnhance.Contrast(top).enhance(1.15)).enhance(1.3)
    bg.paste(top, (0, 30))
    return bg


def _text(img: Image.Image, lines: list[str], credit: str) -> None:
    grad = Image.linear_gradient("L").resize((S, 520)).point(lambda v: int(v * 0.9))
    img.paste(Image.new("RGB", (S, 520), "black"), (0, S - 520), grad)
    d = ImageDraw.Draw(img)
    for text, y, (size, fill, stroke, band) in zip(lines, LINE_Y, LINE_STYLE):
        while True:  # shrink until the line fits
            f = ImageFont.truetype(FONT, size)
            x0, y0, x1, y1 = d.textbbox((0, 0), text, font=f, stroke_width=stroke)
            if x1 - x0 <= MAX_TEXT_W or size <= 40:
                break
            size -= 4
        x = (S - (x1 - x0)) // 2 - x0
        if band:
            d.polygon([(x + x0 - 40, y + y0 - 8), (x + x1 + 50, y + y0 - 18),
                       (x + x1 + 30, y + y1 + 14), (x + x0 - 50, y + y1 + 22)], fill=(190, 0, 0))
        d.text((x, y), text, font=f, fill=fill, stroke_width=stroke, stroke_fill="black")
    cf = ImageFont.truetype(FONT, 24)
    d.text((S - 16 - d.textlength(credit, font=cf), 14), credit, font=cf, fill="white",
           stroke_width=2, stroke_fill="black")


def render(photo: Image.Image, lines: list[str], credit: str, out_path: str,
           person: Image.Image | None = None, background: Image.Image | None = None) -> str:
    """portrait layout when both person and background are given, scene layout otherwise."""
    img = _portrait(person, background) if person is not None and background is not None else _scene(photo)
    _text(img, lines, credit)
    img.save(out_path, "JPEG", quality=90)
    return out_path
