"""
Square news poster for the hot-news photo post — poster.py

Two layouts, both 1080x1080 with three Thai headline lines and a photo credit:
  portrait — the person cut out of the source photo (rembg, face untouched) over an
             AI background (flux-2-klein-4b, generated by the caller)
  scene    — the source photo as a tilted print, its people popping out above it, over a toned
             backdrop with a per-story cartoon effect (rain/storm/fire/money/party); sensitive
             stories get the plain graded photo over a blurred copy of itself

Thai text goes through Pillow's raqm layout (needs libfribidi/libharfbuzz at runtime):
ffmpeg drawtext drops stacked marks such as the ์ in ธิ์ or the ้ in ฮั้ว.
"""

import math
import random
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageEnhance, ImageFilter, ImageFont, ImageOps

FONT = str(Path(__file__).parent / "assets" / "Kanit-Black.ttf")
S = 1080
TEXT_TOP = 700
MAX_TEXT_W = 1000
# (default size, fill, stroke, band behind)
LINE_STYLE = [(88, "white", 5, True), (140, (255, 214, 31), 8, False), (72, "white", 5, False)]
# sensitive stories (death, child victim, sexual crime, disaster): no red/yellow, smaller headline
LINE_STYLE_MUTED = [(88, "white", 5, True), (110, "white", 8, False), (72, "white", 5, False)]
BAND_COLOR = (190, 0, 0)
BAND_COLOR_MUTED = (45, 45, 45)
LINE_Y = [TEXT_TOP, TEXT_TOP + 100, TEXT_TOP + 270]
MIN_PERSON, MAX_PERSON = 0.08, 0.85  # share of the photo the cutout mask must cover


def people(photo: Image.Image) -> Image.Image | None:
    """The people in the photo (RGBA, full photo size, background transparent), or None when the
    mask is too small/large to be a clear subject."""
    from rembg import new_session, remove  # heavy import: onnxruntime + model load

    out = remove(photo.convert("RGB"), session=new_session("u2net_human_seg"))
    alpha = out.getchannel("A")
    cover = sum(alpha.point(lambda v: 1 if v > 128 else 0).getdata()) / (alpha.width * alpha.height)
    print(f"[POSTER] cutout covers {cover:.0%}")
    return out if MIN_PERSON <= cover <= MAX_PERSON else None


def cutout(photo: Image.Image) -> Image.Image | None:
    """Person cutout cropped to its bounding box, or None (see people())."""
    out = people(photo)
    return out.crop(out.getbbox()) if out is not None else None


def _portrait(person: Image.Image, background: Image.Image) -> Image.Image:
    bg = ImageEnhance.Brightness(ImageOps.fit(background.convert("RGB"), (S, S))).enhance(0.8)
    ph = 680
    p = person.resize((round(person.width * ph / person.height), ph), Image.LANCZOS)
    if p.width > S:  # very wide cutouts (two people, arms out): fit width instead
        p = p.resize((S, round(p.height * S / p.width)), Image.LANCZOS)
    # right of centre so the background's key symbols (prompted onto the left half) stay visible
    x = min(S - p.width, max(0, round(S * 0.62 - p.width / 2)))
    bg.paste(p, (x, TEXT_TOP + 50 - p.height), p)
    return bg


# per-story cartoon effect (Gemini picks one) -> backdrop tone (dark, light) for colorize
FX_TONE = {"rain": ((0, 8, 30), (70, 150, 255)), "storm": ((5, 0, 25), (120, 90, 255)),
           "fire": ((30, 0, 0), (255, 120, 10)), "money": ((0, 20, 5), (230, 190, 40)),
           "party": ((25, 0, 35), (255, 60, 170)), "justice": ((10, 5, 30), (210, 165, 60)),
           "police": ((0, 0, 25), (60, 70, 235)), "sport": ((0, 20, 25), (0, 200, 160)),
           "alert": ((25, 18, 0), (245, 195, 0)), "none": ((20, 0, 0), (230, 40, 20))}
EMOJI_FONT = "/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf"  # apt fonts-noto-color-emoji
GOLD, GOLD_DARK = (250, 200, 40, 255), (90, 55, 0, 255)
PX, PY, PW, PH = 70, 40, 940, 640  # the photo print, before its -3 degree tilt
POP = 130  # px of the people's heads/shoulders that break out above the print


def _scene(photo: Image.Image, sensitive: bool = False, pop: Image.Image | None = None,
           fx: str = "none", tag: str = "ข่าวด่วน", emoji: list[str] | None = None,
           tone: tuple | None = None) -> Image.Image:
    photo = photo.convert("RGB")
    bg = ImageOps.fit(photo, (S, S)).filter(ImageFilter.GaussianBlur(40))
    bg = ImageEnhance.Brightness(bg).enhance(0.6)
    if sensitive:  # natural colours, plain full-width photo, no effects
        bg.paste(ImageOps.fit(photo, (S, 680)), (0, 30))
        return bg
    return _scene_print(photo, bg, pop, fx if fx in FX_TONE else "none", tag, emoji or [], tone)


def _fit(im: Image.Image) -> Image.Image:
    """Punch-in crop to the print size (same transform for the photo and its people mask)."""
    return ImageOps.fit(ImageOps.fit(im, (round(PW * 1.12), round(PH * 1.12)), centering=(0.5, 0.35)), (PW, PH))


def _scene_print(photo: Image.Image, blurred: Image.Image, pop: Image.Image | None,
                 fx: str, tag: str, emoji: list[str], tone: tuple | None) -> Image.Image:
    """The photo as a tilted white-bordered print over a toned, speed-lined backdrop with a cartoon
    effect; the people (pop, rembg mask) break out above the print; a stamp pins the top-right corner
    (and covers the source watermark). fx "none": the story's emoji as stickers and its own tone."""
    rng = random.Random(f"{fx}{tag}{photo.size}")
    stickers = emoji if fx == "none" else []
    tone = tone if fx == "none" and tone else FX_TONE[fx]
    bg = ImageOps.colorize(ImageOps.grayscale(blurred), *tone).convert("RGBA")
    streaks = Image.new("RGBA", (S * 2, S * 2))
    sd = ImageDraw.Draw(streaks)
    for i in range(0, S * 2, 46):
        sd.line([(i, 0), (i, S * 2)], fill=(255, 255, 255, 18), width=14)
    bg.alpha_composite(streaks.rotate(28).crop((S // 2, S // 2, S // 2 + S, S // 2 + S)))
    _fx(bg, fx, rng, front=False)
    _stickers(bg, stickers, rng, front=False)

    top = _fit(photo)
    top = ImageEnhance.Color(ImageEnhance.Contrast(top).enhance(1.2)).enhance(1.35)
    top = ImageEnhance.Sharpness(top).enhance(1.4)
    vig = Image.radial_gradient("L").resize((PW, PH)).point(lambda v: int(min(255, v * 1.6) * 0.55))
    top = Image.composite(Image.new("RGB", (PW, PH), "black"), top, vig)

    wt, person = 0, None  # wt: window top inside the print; above it only the people show
    if pop is not None:
        alpha = _fit(pop.getchannel("A"))
        box = alpha.point(lambda v: 255 if v > 128 else 0).getbbox()
        if box and box[1] > 8 and min(box[1] + POP, PH - 380) - box[1] >= 60:
            wt = min(box[1] + POP, PH - 380)
            person = Image.new("RGBA", (S, S))
            person.paste(top, (PX, PY), alpha)

    b = 14
    card = Image.new("RGBA", (S, S))
    ImageDraw.Draw(card).rectangle([PX - b, PY + wt - b, PX + PW + b - 1, PY + PH + b - 1], fill="white")
    card.paste(top.crop((0, wt, PW, PH)), (PX, PY + wt))
    layers = [card]
    if person is not None:  # white sticker outline where the people leave the print
        outline = person.getchannel("A").filter(ImageFilter.MaxFilter(13))
        ImageDraw.Draw(outline).rectangle([0, PY + wt, S, S], fill=0)
        stroke = Image.new("RGBA", (S, S), "white")
        stroke.putalpha(outline)
        layers += [stroke, person]
    layers = [l.rotate(-3, resample=Image.BICUBIC, center=(S / 2, S / 2)) for l in layers]

    shadow_a = layers[0].getchannel("A")
    for l in layers[1:]:
        shadow_a = ImageChops.lighter(shadow_a, l.getchannel("A"))
    shadow = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    shadow.paste((0, 0, 0, 170), mask=shadow_a)
    bg.alpha_composite(shadow.filter(ImageFilter.GaussianBlur(18)), (14, 20))
    for l in layers:
        bg.alpha_composite(l)
    _fx(bg, fx, rng, front=True)
    _stickers(bg, stickers, rng, front=True)

    f = ImageFont.truetype(FONT, 54)
    x0, y0, x1, y1 = f.getbbox(tag)
    stamp = Image.new("RGBA", (x1 - x0 + 56, y1 - y0 + 34), (255, 214, 31, 255))
    td = ImageDraw.Draw(stamp)
    td.rectangle([4, 4, stamp.width - 5, stamp.height - 5], outline=(190, 0, 0), width=5)
    td.text((28 - x0, 17 - y0), tag, font=f, fill=(190, 0, 0))
    stamp = stamp.rotate(8, resample=Image.BICUBIC, expand=True)
    bg.alpha_composite(stamp, (S - stamp.width - 22, PY + wt + (56 if wt == 0 else -30)))
    return bg.convert("RGB")


def _edge_xy(rng: random.Random) -> tuple[int, int]:
    """A point in the side margins or top strip, so front effects never sit on a face."""
    x = rng.choice([rng.randint(0, 110), rng.randint(970, S)])
    return x, rng.randint(80, 660)


def _fx(img: Image.Image, fx: str, rng: random.Random, front: bool) -> None:
    """Cartoon effect drawn onto img: behind the print (front=False) or a light layer over it."""
    layer = Image.new("RGBA", (S, S))
    d = ImageDraw.Draw(layer)
    if fx in ("rain", "storm"):
        if not front:
            for cx, cy in ((90, 30), (S - 110, 20)):  # cartoon clouds peeking over the top corners
                blobs = [(cx + dx, cy + dy, r) for dx, dy, r in
                         ((-90, 20, 60), (-30, -10, 80), (50, 0, 70), (110, 25, 55), (10, 40, 65))]
                for x, y, r in blobs:
                    d.ellipse([x - r - 6, y - r - 6, x + r + 6, y + r + 6], fill=(25, 35, 70, 255))
                for x, y, r in blobs:
                    d.ellipse([x - r, y - r, x + r, y + r], fill=(235, 240, 252, 255))
        for _ in range(28 if front else 130):
            x, y, ln = rng.randint(-60, S), rng.randint(-40, S - 380), rng.randint(28, 58)
            w, a = (4, 120) if front else (6, 210)
            d.line([(x, y), (x - ln * 0.35, y + ln)], fill=(205, 228, 255, a), width=w)
        if front:
            for _ in range(7):  # teardrops
                x, y = _edge_xy(rng)
                r = rng.randint(10, 15)
                d.polygon([(x, y - r * 2.4), (x - r * 0.95, y - r * 0.3), (x + r * 0.95, y - r * 0.3)],
                          fill=(120, 190, 255, 255), outline=(20, 60, 140, 255), width=3)
                d.ellipse([x - r, y - r, x + r, y + r], fill=(120, 190, 255, 255), outline=(20, 60, 140, 255), width=3)
                d.polygon([(x, y - r * 2.2), (x - r * 0.8, y - r * 0.4), (x + r * 0.8, y - r * 0.4)],
                          fill=(120, 190, 255, 255))
                d.ellipse([x - r * 0.45, y - r * 0.5, x - r * 0.1, y - r * 0.05], fill=(255, 255, 255, 230))
        if fx == "storm" and not front:
            for x0, flip in ((60, 1), (S - 60, -1)):  # zigzag bolts at the sides
                pts = [(0, 0), (70, 0), (35, 150), (90, 150), (-10, 400), (20, 210), (-35, 210)]
                bolt = [(x0 + flip * px - flip * 30, 120 + py) for px, py in pts]
                d.polygon(bolt, fill=(255, 232, 40, 255), outline=(20, 10, 0, 255), width=6)
    elif fx == "fire":
        for _ in range(25 if front else 110):
            x, y = _edge_xy(rng) if front else (rng.randint(0, S), rng.randint(0, S - 300))
            r = rng.randint(2, 7)
            d.ellipse([x - r, y - r, x + r, y + r], fill=(255, rng.randint(140, 230), 30, 230))
        if not front:
            for x0 in (40, S - 40):  # cartoon flames rising at the print's sides
                for dx, h, w in ((-30, 260, 90), (30, 200, 80), (0, 320, 100)):
                    for grow, col in ((1.0, (255, 90, 0, 255)), (0.6, (255, 220, 40, 255))):
                        cx, bw, bh = x0 + dx, w * grow, h * grow
                        d.polygon([(cx, 760 - bh), (cx - bw / 2, 760 - bh * 0.35), (cx + bw / 2, 760 - bh * 0.35)], fill=col)
                        d.ellipse([cx - bw / 2, 760 - bh * 0.5, cx + bw / 2, 760], fill=col)
        layer = Image.alpha_composite(layer.filter(ImageFilter.GaussianBlur(5)), layer)
    elif fx == "money":
        cf = ImageFont.truetype(FONT, 34)
        for _ in range(6 if front else 16):
            x, y = _edge_xy(rng) if front else (rng.randint(0, S), rng.randint(0, S - 360))
            r = rng.randint(20, 34)
            d.ellipse([x - r, y - r, x + r, y + r], fill=(255, 200, 30, 255), outline=(140, 85, 0, 255), width=4)
            d.ellipse([x - r + 8, y - r + 8, x + r - 8, y + r - 8], outline=(200, 140, 0, 255), width=3)
            d.text((x, y), "฿", font=cf, fill=(140, 85, 0, 255), anchor="mm")
        for _ in range(8 if front else 14):  # sparkles
            x, y = _edge_xy(rng) if front else (rng.randint(0, S), rng.randint(0, S - 360))
            r = rng.randint(10, 22)
            d.polygon([(x, y - r), (x + r / 4, y - r / 4), (x + r, y), (x + r / 4, y + r / 4),
                       (x, y + r), (x - r / 4, y + r / 4), (x - r, y), (x - r / 4, y - r / 4)], fill=(255, 250, 200, 255))
    elif fx == "party":
        colours = [(255, 60, 90), (255, 214, 31), (40, 200, 255), (120, 255, 120), (255, 255, 255)]
        for _ in range(30 if front else 110):
            x, y = _edge_xy(rng) if front else (rng.randint(0, S), rng.randint(0, S - 360))
            a, w, h = rng.uniform(0, 3.14), rng.randint(5, 9), rng.randint(12, 20)
            ca, sa = math.cos(a), math.sin(a)
            pts = [(x + px * ca - py * sa, y + px * sa + py * ca) for px, py in
                   ((-w, -h), (w, -h), (w, h), (-w, h))]
            d.polygon(pts, fill=(*rng.choice(colours), 255))
    elif fx == "justice":
        _justice(d, layer, rng, front)
    elif fx == "police":
        layer = _police(rng, front)
    elif fx == "sport":
        _sport(d, layer, rng, front)
    elif fx == "alert":
        _alert(d, layer, rng, front)
    img.alpha_composite(layer)


def _sparkle(d: ImageDraw.ImageDraw, x: float, y: float, r: float, fill) -> None:
    d.polygon([(x, y - r), (x + r / 4, y - r / 4), (x + r, y), (x + r / 4, y + r / 4),
               (x, y + r), (x - r / 4, y + r / 4), (x - r, y), (x - r / 4, y - r / 4)], fill=fill)


def _paste_rotated(layer: Image.Image, part: Image.Image, angle: float, cx: int, cy: int) -> None:
    part = part.rotate(angle, resample=Image.BICUBIC, expand=True)
    layer.alpha_composite(part, (cx - part.width // 2, cy - part.height // 2))


def _justice(d, layer, rng, front) -> None:
    """Gold scales of justice top-left, a gavel top-right, peeking round the print; sparkles in front."""
    if front:
        for _ in range(8):
            _sparkle(d, *_edge_xy(rng), rng.randint(10, 20), (255, 245, 190, 255))
        return
    sc = Image.new("RGBA", (330, 300))
    sd = ImageDraw.Draw(sc)
    ol = dict(fill=GOLD, outline=GOLD_DARK, width=5)
    sd.rectangle([155, 40, 175, 250], **ol)                       # post
    sd.polygon([(105, 290), (225, 290), (190, 248), (140, 248)], **ol)  # base
    sd.rectangle([20, 52, 310, 70], **ol)                         # beam
    for x in (40, 290):
        sd.line([(x, 70), (x - 32, 175)], fill=GOLD_DARK, width=4)
        sd.line([(x, 70), (x + 32, 175)], fill=GOLD_DARK, width=4)
        sd.pieslice([x - 50, 130, x + 50, 220], 0, 180, **ol)    # pan
    sd.ellipse([145, 12, 185, 52], **ol)                          # knob
    _paste_rotated(layer, sc, 8, 120, 130)
    g = Image.new("RGBA", (300, 240))
    gd = ImageDraw.Draw(g)
    gd.rectangle([138, 70, 162, 235], fill=(150, 85, 30, 255), outline=(60, 30, 0, 255), width=5)  # handle
    gd.rounded_rectangle([40, 10, 260, 90], radius=18, fill=(170, 100, 40, 255), outline=(60, 30, 0, 255), width=6)
    gd.rectangle([70, 10, 90, 90], fill=GOLD, outline=(60, 30, 0, 255), width=4)   # gold bands
    gd.rectangle([210, 10, 230, 90], fill=GOLD, outline=(60, 30, 0, 255), width=4)
    _paste_rotated(layer, g, -35, S - 110, 150)


def _police(rng, front) -> Image.Image:
    """Red and blue siren glow from the top corners with fanned light rays; lens flares in front."""
    layer = Image.new("RGBA", (S, S))
    d = ImageDraw.Draw(layer)
    if front:
        for _ in range(5):
            x, y = _edge_xy(rng)
            r = rng.randint(14, 30)
            d.ellipse([x - r, y - r, x + r, y + r], fill=(255, 255, 255, 70))
            _sparkle(d, x, y, r * 1.6, (255, 255, 255, 200))
        return layer.filter(ImageFilter.GaussianBlur(1))
    for (cx, cy), col in (((0, 0), (255, 30, 30)), ((S, 0), (40, 90, 255))):
        for i in range(9):  # fanned rays
            a = math.radians((i * 10 + (0 if cx == 0 else 90)) + 2)
            b = a + math.radians(4)
            d.polygon([(cx, cy), (cx + math.cos(a) * 1500, cy + math.sin(a) * 1500),
                       (cx + math.cos(b) * 1500, cy + math.sin(b) * 1500)], fill=(*col, 55))
        d.ellipse([cx - 330, cy - 330, cx + 330, cy + 330], fill=(*col, 170))
    return layer.filter(ImageFilter.GaussianBlur(28))


def _sport(d, layer, rng, front) -> None:
    """Horizontal motion streaks and a gold trophy top-left; sparkles in front."""
    if front:
        for _ in range(9):
            _sparkle(d, *_edge_xy(rng), rng.randint(10, 22), (255, 250, 210, 255))
        return
    for _ in range(40):
        y, x, ln = rng.randint(0, S - 360), rng.randint(-200, S), rng.randint(120, 420)
        d.line([(x, y), (x + ln, y)], fill=(255, 255, 255, rng.randint(40, 110)), width=rng.randint(4, 12))
    t = Image.new("RGBA", (280, 320))
    td = ImageDraw.Draw(t)
    ol = dict(fill=GOLD, outline=GOLD_DARK, width=6)
    td.arc([10, 40, 100, 150], 90, 270, fill=GOLD_DARK, width=16)    # handles
    td.arc([180, 40, 270, 150], 270, 90, fill=GOLD_DARK, width=16)
    td.arc([14, 44, 96, 146], 90, 270, fill=GOLD, width=8)
    td.arc([184, 44, 266, 146], 270, 90, fill=GOLD, width=8)
    td.chord([50, -90, 230, 200], 0, 180, **ol)                      # cup
    td.rectangle([122, 196, 158, 250], **ol)                          # stem
    td.rectangle([80, 248, 200, 300], **ol)                           # base
    _sparkle(td, 110, 60, 22, (255, 255, 230, 255))
    _paste_rotated(layer, t, 10, 120, 150)


def _alert(d, layer, rng, front) -> None:
    """Yellow-black caution tape across the top corners and warning signs in the margins."""
    tape = Image.new("RGBA", (1100, 70), (255, 214, 0, 255))
    kd = ImageDraw.Draw(tape)
    for x in range(-70, 1100, 70):
        kd.polygon([(x, 70), (x + 35, 70), (x + 70, 0), (x + 35, 0)], fill=(20, 20, 20, 255))
    kd.rectangle([0, 0, 1099, 69], outline=(20, 20, 20, 255), width=4)
    if front:  # tape over the print's top-left corner
        _paste_rotated(layer, tape, 38, 90, 110)
        return
    _paste_rotated(layer, tape, -38, S - 60, 90)
    f = ImageFont.truetype(FONT, 58)
    for _ in range(6):
        x, y = rng.randint(0, S), rng.randint(0, S - 380)
        r = rng.randint(36, 56)
        pts = [(x, y - r), (x + r * 1.1, y + r * 0.8), (x - r * 1.1, y + r * 0.8)]
        d.polygon(pts, fill=(255, 214, 0, 255), outline=(20, 20, 20, 255), width=6)
        d.text((x, y + r * 0.2), "!", font=f.font_variant(size=int(r * 1.1)), fill=(20, 20, 20, 255), anchor="mm")


def _emoji_sprite(ch: str, size: int) -> Image.Image | None:
    """One colour emoji with a white sticker outline, or None when it can't be drawn."""
    try:
        f = ImageFont.truetype(EMOJI_FONT, 109)  # Noto's bitmap strike: only size 109 renders
    except OSError:
        print("[POSTER] no colour emoji font -> emoji skipped")
        return None
    im = Image.new("RGBA", (180, 160))
    ImageDraw.Draw(im).text((10, 10), ch, font=f, embedded_color=True)
    box = im.getbbox()
    if box is None:
        return None
    im = im.crop(box)
    im = im.resize((size, round(im.height * size / im.width)), Image.LANCZOS)
    pad = Image.new("RGBA", (im.width + 20, im.height + 20))
    pad.alpha_composite(im, (10, 10))
    white = Image.new("RGBA", pad.size, "white")
    white.putalpha(pad.getchannel("A").filter(ImageFilter.MaxFilter(9)))
    white.alpha_composite(pad)
    return white


def _stickers(img: Image.Image, emoji: list[str], rng: random.Random, front: bool) -> None:
    """The story's emoji scattered as tilted stickers: many behind the print, a few big in the margins."""
    sprites = [s for s in (_emoji_sprite(e, 120) for e in emoji) if s is not None]
    if not sprites:
        return
    for i in range(4 if front else 6):
        sp = sprites[i % len(sprites)]
        k = rng.uniform(0.8, 1.1) if front else rng.uniform(0.5, 0.9)
        sp = sp.resize((round(sp.width * k), round(sp.height * k)), Image.LANCZOS)
        sp = sp.rotate(rng.uniform(-25, 25), resample=Image.BICUBIC, expand=True)
        x, y = _edge_xy(rng)  # margins only: the popped-out heads own the top middle
        img.alpha_composite(sp, (max(0, min(S - sp.width, x - sp.width // 2)), max(0, y - sp.height // 2)))


def _text(img: Image.Image, lines: list[str], credit: str, sensitive: bool = False) -> None:
    style = LINE_STYLE_MUTED if sensitive else LINE_STYLE
    band_color = BAND_COLOR_MUTED if sensitive else BAND_COLOR
    grad = Image.linear_gradient("L").resize((S, 520)).point(lambda v: int(v * 0.9))
    img.paste(Image.new("RGB", (S, 520), "black"), (0, S - 520), grad)
    d = ImageDraw.Draw(img)
    for text, y, (size, fill, stroke, band) in zip(lines, LINE_Y, style):
        while True:  # shrink until the line fits
            f = ImageFont.truetype(FONT, size)
            x0, y0, x1, y1 = d.textbbox((0, 0), text, font=f, stroke_width=stroke)
            if x1 - x0 <= MAX_TEXT_W or size <= 40:
                break
            size -= 4
        x = (S - (x1 - x0)) // 2 - x0
        if band:
            d.polygon([(x + x0 - 40, y + y0 - 8), (x + x1 + 50, y + y0 - 18),
                       (x + x1 + 30, y + y1 + 14), (x + x0 - 50, y + y1 + 22)], fill=band_color)
        d.text((x, y), text, font=f, fill=fill, stroke_width=stroke, stroke_fill="black")
    cf = ImageFont.truetype(FONT, 24)
    d.text((16, 14), credit, font=cf, fill="white",
           stroke_width=2, stroke_fill="black")


def render(photo: Image.Image, lines: list[str], credit: str, out_path: str,
           person: Image.Image | None = None, background: Image.Image | None = None,
           sensitive: bool = False, pop: Image.Image | None = None, fx: str = "none",
           tag: str = "ข่าวด่วน", emoji: list[str] | None = None, tone: tuple | None = None) -> str:
    """portrait layout when both person and background are given, scene layout otherwise.
    Scene: pop = people() mask of photo (they break out of the print), fx = FX_TONE key, tag = stamp word;
    fx "none": emoji stickers and tone ((dark rgb), (light rgb)) for the backdrop.
    sensitive (death, child victim, sexual crime, disaster): muted style, natural-colour photo."""
    img = (_portrait(person, background) if person is not None and background is not None
           else _scene(photo, sensitive, pop, fx, tag, emoji, tone))
    _text(img, lines, credit, sensitive)
    img.save(out_path, "JPEG", quality=90)
    return out_path
